Data = {};

Data.luckscore = [
  "Harsh winter: all attack rolls",
  "Taurus: Melee attack rolls",
  "Fortunate Date: Missile fire attack rolls",
  "Raised by wolves: Unarmed attack rolls",
  "Concieved on horseback: Mounted attack rolls",
  "Born on the battlefield: Damage rolls",
  "Path of the bear: Melee damage rolls",
  "Hawkeye: Missle fire damage rolls",
  "Pack hunter: Attack and damage rolls for 0-level trained weapon",
  "Born under the loom: Skill checks (including thief skills)",
  "Fox's cunning: Find/disable traps",
  "Four-leafed clover: find secret doors",
  "Seventh son: Spell checks",
  "The raging storm: Spell damage",
  "Righteous heart: Turn unholy checks",
  "Survived the plague: Magical healing",
  "Lucky sign: Saving throws",
  "Guardian angel: Saving throws to escape traps",
  "Survived a spider bite: Saving throws against poison",
  "Struck by lightning: Reflex saving throws",
  "Lived through famine: Fortitude saving throws",
  "Resisted temptation: Willpower saving throws",
  "Charmed house: armor class",
  "Speed of the cobra: initaitve",
  "Bountiful harvest: Hit points (applies at each level)",
  "Warrior's arm: Critical hit tables (modifier is doubled)",
  "Unholy house: corruption rolls",
  "The broken star: fumbles (modifier is doubled)",
  "Birdsong: Number of languages",
  "Wild child: Speed (each +1 = +5' speed)"
];

Data.equipment = [
  "backpack (2gp)",
  "candle (1 cp)",
  "chain 10' (30 gp)",
  "chalk, 1 piece (1 cp)",
  "chest, empty (2 gp)",
  "crowbar (2 gp)",
  "flask, empty (3 cp)",
  "flint & steel (15 cp)",
  "gappling hook (1 gp)",
  "hammer, small (5 sp)",
  "holy symbol (25 gp)",
  "holy water, 1 vial (25 gp)",
  "iron spikes, each (1 sp)",
  "latern (10 gp)",
  "mirror, hand-sized (10 gp)",
  "oil, 1 flask (2 sp)",
  "pole, 10 foot (15 cp)",
  "rations, per day (5 cp)",
  "rope, 50' (25 cp)",
  "sack, large (12 cp)",
  "sack, small (8 cp)",
  "thieves' tools (25 gp)",
  "torch, each (1 cp)",
  "waterskin (5 sp)"
];

Data.occupation = [
  {name:'alchemist', trainedWeapon:'staff (1d4)', item:'oil, 1 flask', weight:1},
  {name:'animal trainer', trainedWeapon:'club (1d4)', item:'pony', weight:1},
  {name:'armorer', trainedWeapon:'hammer (as club) (1d4)', item:'iron helmet (+1 AC)', weight:2},
  {name:'astrologer', trainedWeapon:'dagger (1d4)', item:'spyglass', weight:1},
  {name:'blacksmith', trainedWeapon:'hammer (as club) (1d4)', item:'steel tongs', weight:3},
  {name:'caravan guard', trainedWeapon:'short sword (1d6)', item:'linen, 1 yard', weight:2},
  {name:'cobbler', trainedWeapon:'awl (as dagger) (1d4)', item:'shoehorn', weight:1},
  {name:'confidence artist', trainedWeapon:'dagger (1d4)', item:'quality cloak', weight:1},
  {name:'cooper', trainedWeapon:'crowbar (as club) (1d4)', item:'barrel', weight:1},
  {name:'cutpurse', trainedWeapon:'dagger (1d4)', item:'small chest', weight:2},
  {name:'ditch digger', trainedWeapon:'shovel (as staff) (1d4)', item:'fine dirt, 1 lb', weight:2},
  {name:'dwarven blacksmith', trainedWeapon:'hammer (as club) (1d4)', item:'mithril, 1oz', weight:4},
  {name:'dwarven herder', trainedWeapon:'staff (1d4)', item:'sow', weight:2},
  {name:'dwarven miner', trainedWeapon:'pick (as club) (1d4)', item:'lantern', weight:4},
  {name:'elven artisan', trainedWeapon:'staff (1d4)', item:'clay, 1 lb', weight:4},
  {name:'elven forester', trainedWeapon:'staff (1d4)', item:'herbs, 1 lb', weight:4},
  {name:'elven sage', trainedWeapon:'dagger (1d4)', item:'parchment and quill pen', weight:2},
  {name:'farmer', trainedWeapon:'pitchfork (as spear) (1d8)', item:'hen', weight:10},
  {name:'fortune-teller', trainedWeapon:'dagger (1d4)', item:'tarot deck', weight:1},
  {name:'gambler', trainedWeapon:'club (1d4)', item:'dice', weight:1},
  {name:'gongfarmer', trainedWeapon:'trowel (as dagger) (1d4)', item:'sack of night soil', weight:1},
  {name:'grave digger', trainedWeapon:'shovel (as staff) (1d4)', item:'trowel', weight:2},
  {name:'guild beggar', trainedWeapon:'sling (1d4)', item:'crutches', weight:2},
  {name:'halfling gypsy', trainedWeapon:'sling (1d4)', item:'hex doll', weight:4},
  {name:'halfling trader', trainedWeapon:'short sword (1d6)', item:'20 sp', weight:4},
  {name:'halfling vagrant', trainedWeapon:'club (1d4)', item:'begging bowl', weight:2},
  {name:'healer', trainedWeapon:'club (1d4)', item:'holy water, 1 vial', weight:1},
  {name:'herbalist', trainedWeapon:'club (1d4)', item:'herbs, 1 lb', weight:1},
  {name:'herder', trainedWeapon:'staff (1d4)', item:'herding dog', weight:3},
  {name:'hunter', trainedWeapon:'shortbow (1d6)', item:'deer pelt', weight:3},
  {name:'indentured servant', trainedWeapon:'staff (1d4)', item:'locket', weight:1},
  {name:'jester', trainedWeapon:'dart (1d4)', item:'silk clothes', weight:1},
  {name:'jeweler', trainedWeapon:'dagger (1d4)', item:'gem worth 20gp', weight:1},
  {name:'locksmith', trainedWeapon:'dagger (1d4)', item:'fine tools', weight:1},
  {name:'mercenary', trainedWeapon:'longsword', item:'hide armor (+3 AC)', weight:1},
  {name:'miller/baker', trainedWeapon:'club (1d4)', item:'flour, 1 lb', weight:1},
  {name:'minstrel', trainedWeapon:'dagger (1d4)', item:'ukulele', weight:1},
  {name:'noble', trainedWeapon:'longsword (1d8)', item:'gold ring worth 10 gp', weight:1},
  {name:'orphan', trainedWeapon:'club (1d4)', item:'rag doll', weight:1},
  {name:'ostler', trainedWeapon:'staff (1d4)', item:'bridle', weight:1},
  {name:'outlaw', trainedWeapon:'short sword (1d6)', item:'leather armor (+2 AC)', weight:1},
  {name:'scribe', trainedWeapon:'dart (1d4)', item:'parchment, 10 sheets', weight:1},
  {name:'shaman', trainedWeapon:'mace (1d6)', item:'herbs, 1 lb', weight:1},
  {name:'slave', trainedWeapon:'club (1d4)', item:'strange-looking rock', weight:1},
  {name:'smuggler', trainedWeapon:'sling (1d4)', item:'waterproof sack', weight:1},
  {name:'soldier', trainedWeapon:'spear (1d8)', item:'shield (+1 AC)', weight:2},
  {name:'squire', trainedWeapon:'longsword (1d8)', item:'steel helmet (+1 AC)', weight:2},
  {name:'trapper', trainedWeapon:'sling (1d4)', item:'badger pelt', weight:2},
  {name:'urchin', trainedWeapon:'stick (as club) (1d4)', item:'begging bowl', weight:1},
  {name:'wainwright', trainedWeapon:'club (1d4)', item:'pushcart', weight:1},
  {name:'weaver', trainedWeapon:'dagger (1d4)', item:'fine suit of clothes', weight:1},
  {name:'wizard\'s apprentice', trainedWeapon:'dagger (1d4)', item:'black grimoire', weight:1},
  {name:'woodcutter', trainedWeapon:'handaxe (1d6)', item:'bundle of wood', weight:3}
];

Data.alignment = ["lawful", "neutral", "chaotic"];
